version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: sidvi990/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: sidvi990/foodgram-frontend:latest
    volumes:
      - frontend_value:/app/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - frontend_value:/usr/share/nginx/html/
      - static_value:/usr/share/nginx/html/backend_static/
      - media_value:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  frontend_value:
  db_data:
