# Generated by Django 2.2.16 on 2023-04-22 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230419_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('recipe',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('recipe',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Должно быть больше нуля!'), django.core.validators.MaxValueValidator(limit_value=32000, message='Слишком долго для приготовления!')], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Нельзя приготовить блюдо настолько быстро!'), django.core.validators.MaxValueValidator(limit_value=600, message='Слишком долго для приготовления!')], verbose_name='Время приготовления'),
        ),
    ]
